### ISSUE TITLE
IP address Report

### ISSUE THREAD

**Issue by lavermil** [AsBuiltReport/AsBuiltReport.Nutanix.PrismElement#15]
**Is your feature request related to a problem? Please describe.**
It is always important to know the current usage of IP addressing in subnets. Collecting information can be difficult.

**Describe the solution you'd like**
It would be really useful to have an IP address Report as part of the export. This would allow for easy input into a IPAM, spread sheet, DB, etc. The idea would be to have this in a list of individual IPs. So each IP address would be on a line/row of its own.
Maybe the columns would be something like below.
IP(v4/v6),VMName,vNIC,VLAN#,SubnetName,IPAMMethod,vSwitch,Node/Host,Cluster,Location

**Describe alternatives you've considered**
Writing my own script to do the same thing but this is a nice solution and would benefit others so coding in a vacuum is not ideal.

**Additional context**
None

**Comment by tpcarman** [comment]
AsBuiltReport relies on [PScribo](https://github.com/iainbrighton/PScribo), to produce the document outputs. At present there is no ability, nor plans to support an export feature for Excel. While I have considered a feature like this, it simply would not work within the current framework, and therefore I do not plan to implement it.

**Comment by lavermil** [comment]
Nice work on the code BTW!

I was actually referring to an integrated section in the report as a table thus allowing people to easy copy/paste to excel/etc. If you still don't want to include stuff like this that is ok. I will fork it and add it so I can manually keep it there. 

Here is an ugly example of what I did (I am not a code I am quick scripter). For some reason I cannot get `$NetworkAddresses` to update when I cycle through each PE.

Invoke-AsBuiltReport.Nutanix.PrismElement.ps1 
Add support for more than one Target (via csv) like the example says @ line 30
change 
`foreach ($NtnxPE in $Target) {`
to
`foreach ($NtnxPE in $Target.split(',')) {`

Update the verbose message so you know which PE is being worked on @ line 32
change
`Write-PScriboMessage "Performing API reference calls"`
to
`Write-PScriboMessage "Performing API reference calls on $($NtnxPE)"`

Add teh IP Report code @ line 1338 insert
```

    }
    #region IP Address Report
    Write-PScriboMessage "IP Address Report InfoLevel set at $($InfoLevel.IPReport)."
    if ($InfoLevel.IPReport -gt 0) {
        #region IP Address Report per Cluster
        Section -Style Heading3 'IP Address Report' {
            $NetworkAddresses = @()
            foreach ($NtnxPE in $Target.split(',')) {
                $NtnxNetworks = (Get-NtnxApi -Version 2 -Uri '/networks').entities | Sort-Object Name
                Write-PScriboMessage "Processing cluster $($NtnxPE)"
                Write-PScriboMessage "Creating Network Hashtable Lookup"
                $NtnxNetworkLookup = @{}
                $NtnxNetworkVlanLookup = @{}
                foreach ($NtnxNetwork in $NtnxNetworks) {
                    $NtnxNetworkLookup.($NtnxNetwork.uuid) = $NtnxNetwork.name
                    $NtnxNetworkVlanLookup.($NtnxNetwork.uuid) = $NtnxNetwork.vlan_id
                }
                # Todo Add in Hosts, and non VM IP collection.
                #region Harvest IPs from VM NICs
                foreach ($NtnxVM in $NtnxVirtualMachines) {
                    $NtnxVMNics = (Get-NtnxApi -Version 2 -Uri $('/vms/' + $($NtnxVM.uuid) + '/nics')).entities | Sort-Object network_uuid
                    if ($NtnxVMNics) {
                        # Update the IP Address Report List
                        $NetworkAddresses += foreach ($NtnxVMNic in $NtnxVMNics) {
                            foreach ( $VMNic_ip_address in $NtnxVMNic.ip_addresses | Sort-Object ) {
                                [PSCustomObject]@{
                                    #ToDo: Find a way to get the 'Port Name' for VMware
                                    'IP Address' = $VMNic_ip_address
                                    'VM Name' = $NtnxVM.vmName
                                    'MAC Address' = $NtnxVMNic.mac_address
                                    'VLAN ID' = $NtnxNetworkVlanLookup."$($NtnxVMNic.network_uuid)"
                                    'Network Name' = $NtnxNetworkLookup."$($NtnxVMNic.network_uuid)"
                                    'Host' = Switch ($NtnxVM.hostName) {
                                        $null { '--' }
                                        default { $NtnxVM.hostName }
                                    }
                                }
                            }
                        }
                    }
                }
                Write-PScriboMessage "Processed $($NetworkAddresses.Count) IPs for cluster $($NtnxPE)"
            }
            #endregion Harvest IPs from VM NICs
            $TableParams = @{
                Name = "IP Address Report"
            }
            # Build different table format based on hypervisor type
            Switch ( $NtnxVM.hypervisorType ) {
                'kVMware' {
                    $TableParams['Columns'] = 'Adapter Type', 'MAC Address', 'IP Address', 'Connected'
                    $TableParams['ColumnWidths'] = 25, 25, 25, 25
                }
                'kKVM' {
                    $TableParams['Columns'] = 'IP Address', 'VM Name', 'MAC Address', 'VLAN ID', 'Network Name', 'Host'
                    $TableParams['ColumnWidths'] = 20, 20, 20, 5, 20, 15
                }
            }
            if ($Report.ShowTableCaptions) {
                $TableParams['Caption'] = "- $($TableParams.Name)"
            }
            if ( $NetworkAddresses ) { $NetworkAddresses | Sort-Object { $_.'IP Address' -as [Version] } | Table @TableParams }
        }
        #endregion IP Address Report per Cluster
    }
    #endregion IP Address Report
```

**Comment by lavermil** [comment]
@tpcarman Any difference in your opinion based on what I provided above?
