### ISSUE TITLE
You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by sourcil8** [AsBuiltReport/AsBuiltReport.Nutanix.PrismElement#17]
**Describe the bug**
VERBOSE: [ 09:29:39:222 ] [ Document ] - Processing section 'Licensing' started.
New-AsBuiltReport: You cannot call a method on a null-valued expression.

**Expected behavior**
when i launch the script, with admin right on Prism Element, Ip and user admin - password correct.. always this error message.. when the script Process the section 'Licensing' apparently
always at this moment, at this check

**Screenshots**
![Untitled](https://github.com/AsBuiltReport/AsBuiltReport.Nutanix.PrismElement/assets/169802883/0eae499d-561e-42ce-a935-15afe1cd5022)

**Desktop (please complete the following information):**
 - OS: AOS 6.0.7.6 STS - PC 2023.4 - ahv 8-20230302 
- Powershell : 
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by tpcarman** [comment]
Please refer to #16 and try and implement the workaround.
