### ISSUE TITLE
New-AsBuiltReport : The remote server returned an error: (412) Precondition Failed

### ISSUE THREAD

**Issue by JackIsenberg** [AsBuiltReport/AsBuiltReport.Nutanix.PrismElement#5]
*** Bug Description ***
Receiving the following error when trying to run New-AsBuiltReport against a Nutanix cluster:

```
New-AsBuiltReport : The remote server returned an error: (412) Precondition Failed.
At line:1 char:1
+ New-AsBuiltReport -Report Nutanix.PrismElement -Target 10.118.17.30 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport
```

*** To Reproduce (Method 1) ***
1. Open PowerShell (standard user or Administrator)
2. Run: `$nxUser = "<Nutanix Username>"`
3. Run: `$nxPassword = ConvertTo-SecureString "<Nutanix Password>" -AsPlainText -Force`
4. Run: `$nxCredentials = New-Object System.Management.Automation.PSCredential ( $nxUser, $nxPassword )`
5. Run: `New-AsBuiltReport -Report Nutanix.PrismElement -Target <Nutanix Prism Element Cluster VIP> -Credential $nxCredentials -Format Word -Orientation Portrait -OutputPath 'C:\!Incoming\'`
6. Process requested information prompts
7. See error

*** To Reproduce (Method 2) ***
1. Open PowerShell (standard user or Administrator)
2. Run: `New-AsBuiltReport -Report Nutanix.PrismElement -Target <Nutanix Prism Element Cluster VIP> -Username '<Nutanix Username>' -Password '<Nutanix Password>' -Format Word -Orientation Portrait -OutputPath 'C:\!Incoming\'`
3. Process requested information prompts

**Expected behavior**
Expecting As Built Report to be generated at 'C:\!Incoming'

**Screenshots**

*** Environment Information ***
 - OS Version(s): Windows 10 Enterprise 1909, Windows Server 2016 Standard
 - PowerShell Version(s): 5.1.18362.628, 5.1.14393.3471
 - Nutanix Cmdlets Version: 2.1.2
 - Nutanix AOS Version: 5.10.9.1 LTS
 - Browser Version: N/A
 - Module Version (AsBuiltReport.Core): 1.0.3
 - Module Version (AsBuiltReport.Nutanix.PrismElement): 0.1.0
 - PSSnapin Version (NutanixCmdletsPSSnapin): 5.1

*** Additional Context ***
- Nutanix Prism Element user is 'admin', with full cluster and user rights to target cluster
- Nutanix Prism Element login has been tested successfully with the standard Nutanix Cmdlets PSSnapin, running `Connect-NTNXCluster -Server 10.118.17.30 -Password $nxPassword -UserName admin -AcceptInvalidSSLCerts`
    - NOTE: The password must be before the username because of a bug (See: [https://next.nutanix.com/scripts-32/connect-ntnxcluster-gives-a-count-cannot-be-less-than-zero-27925](https://next.nutanix.com/scripts-32/connect-ntnxcluster-gives-a-count-cannot-be-less-than-zero-27925))
- The above issue has been reproduced over VPN and on local server via RDP

**Comment by tpcarman** [comment]
@JackIsenberg I'm currently working on improvements to this report. I suggest you try the code in the `dev` branch. Let me know if you find any other issues.

**Comment by tpcarman** [comment]
Please try the latest `AsBuiltReport.Nutanix.PrismElement` module to see if this resolves your issue. Please reopen this case if the issue persists.
